### ISSUE TITLE
Adicionar informações referentes ao projeto no README do projeto

### ISSUE THREAD

**Issue by eliseuegewarth** [fga-gpp-mds/agr-react-native#10]
Adicionar as informações pertinentes ao README do projeto.
Objetivo:
- Tornar claro o propósito do projeto
- Indicar o status do projeto
- Informar principais dependências do projeto
- Prover informações sobre a instalação do projeto

**Comment by alvesisaque** [comment]
A milestone dessa issue deve ser alterada para sprint 1,  por que na sprint 0 a equipe não tinha o escopo definido, impossibilitando o trabalho.
