### ISSUE TITLE
Reunião com Designer do Lappis

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#131]
Reunião realisada segunda as 16:00h.
Pauta da reunião:
- Usabilidade;
- Acessibilidade;
- User Experience;
- Duvidas sobre implementação das funcionalidades de agenda, lista de médicos, "main", barra lateral;
- Paleta de cores.

**Comment by egewarth** [comment]
Mapear processo do cliente a nivel de ação (ver doc de requisitos @gag2502  e @egewarth).
Mapa de interação.
Mapa de interação detalhado (wireframe). 
oq funciona e oq não funciona? perguntar para Dulce
Qual a necessidade real?

**Comment by BeatrizHanae** [comment]
Algumas dicas de Métodos e ferramentas interessantes para o Desenvolvimento de um Produto, de acordo com o curso da Udemy:
Seção 3 - Métodos e Ferramentas - Estratégia de Produto: Golden Path
Seção 3 - Métodos e Ferramentas - Estratégia de Produto: Personas
Seção 3 - Métodos e Ferramentas - Estratégia de Produto: BluePrints (o "na prática", é um exemplo bom para entender porq q a Dulce quer mudar de dispositivo.)
Seção 4 - Métodos e Ferramentas - Geração de ideias: Fluxo do usuário 
Seção 4 - Métodos e Ferramentas - Geração de ideias: Sitemaps (similar ao mapa de interação)
Seção 4 - Métodos e Ferramentas - Geração de ideias: Moodboard (ótimo para referência de cores e imagens)
Seção 7 - Métodos e Ferramentas -Desenho de interfaces : WireFrames

**Comment by gag2502** [comment]
@BeatrizHanae Que linda ❤️  ... Obrigada Hanae
