### ISSUE TITLE
Criar Documento de Arquitetura

### ISSUE THREAD

**Issue by gabibguedes** [fga-gpp-mds/agr-react-native#20]
Exemplos de documento de arquitetura:
https://github.com/fga-gpp-mds/2017.2-MerendaMais/wiki/Documento-de-Arquitetura
Merenda Mais: App React Native
https://github.com/Desenho-2-2017/Ecom_merci/wiki/Documento-de-Arquitetura
Exemplos de documento de visão:
https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Documento-de-Vis%C3%A3o
https://github.com/Desenho-2-2017/Ecom_merci/wiki/Documento-de-Vis%C3%A3o
https://github.com/Software-Design-2017/EmbelezaMais/wiki/Documento-de-Vis%C3%A3o-Framework
Exemplos de Especificação Suplementar:
https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Especifica%C3%A7%C3%A3o-Suplementar

**Comment by gag2502** [comment]
Babys eu vou colocar mais comentários sobre o documento de vocês aqui , mas até agora eu pude perceber algumas coisas que devem ser mudadas : 

:-1:  Escopo e finalidade estão praticamente iguais , sendo que a parte do escopo está melhor descrita do que finalidade , embora também esteja errada . Essa frase " produzido em React Native " está bem ruim , os termos usados em escopo para falar da tecnologia estão melhores.
:-1: Façam a própria representação da arquitetura, não apenas copiem e colem no documento, por dois motivos :  direitos autorais e o documento está em português , então a diagramação e ilustrações devem ser em português também
:-1: Eu vi a palavra "esplanar" no documento , mas seria "explanar" , não acham ? 

Pontos positivos : 
:+1:  Muito organizado 
:+1:  Sumário muito bom 
:+1:  Se esforçaram pra colocar um esquema de representação da arquitetura
Parabéns pessoal , estão indo muito bem :1st_place_medal:

**Comment by fepas** [comment]
Realizaremos as mudanças necessárias e reenviaremos para reavaliação.

**Comment by gag2502** [comment]
1.1 Finalidade
:+1:  Está bem sucinto 
:-1:  "O documento arquitetura ", podem usar o termo "documento de arquitetura" , porque assim parece que o nome do documento é "arquitetura" , e isso é errado

2. Representação da Arquitetura
:-1:  A imagem representando a arquitetura continua a mesma 
:-1:  A secretaria vai fornecer uma base de dados, não um banco
- https://www.luis.blog.br/banco-de-dados-e-sql-diferenca-entre-base-de-dados-e-banco-de-dados/

Diagrama de Classes
:+1:  Está com uma abstração legal do problema
:-1:  Acoplamento muito alto !!! Esse tanto de composição está deixando tudo muito "dependente" e isso é muito ruim

Estão indo bem meninos ... Parabéns :heart: 
@gabibguedes @fepas @EzequielDeOliveira

**Comment by gabibguedes** [comment]
Gabi,
Obrigada pela avaliação, já estamos arrumando os erros restantes

**Comment by gabibguedes** [comment]
Gabi, uma pergunta, vai precisar dos diagramas de pacote e de banco nessa versão inicial do documento de arquitetura?

@gag2502

**Comment by gabibguedes** [comment]
Mudanças a serem feitas no doc de arquitetura
tirar tópico 1.3 e colocar um link para o glossário;
mudar referências para referências bibliográficas ou bibliografia;
tirar tópico 1.5;
arrumar o diagrama de classe tirando o nome "Classname"

**Comment by gabibguedes** [comment]
Arrumar também a setas de herança e diminuir a dependência entre as classes no diagrama de classes

**Comment by gabibguedes** [comment]
Mudar também de AGR para Dulce
