### ISSUE TITLE
Criar Documento de Visão

### ISSUE THREAD

**Issue by gdeusdara** [fga-gpp-mds/agr-react-native#21]
- [x] Estruturar (Fazer um sumário e template do documento);

- [x] Descrever (Definir os itens criados);

- [x] Versão 1.0;

**Comment by alvesisaque** [comment]
# DICA 
Utilizar as seguintes pesquisas para a identificação do problema abordado no projeto!
(fishbone e outros)
- https://g1.globo.com/df/distrito-federal/noticia/bancos-de-leite-de-brasilia-estao-no-limite-diz-secretaria-de-saude.ghtml
- https://g1.globo.com/df/distrito-federal/noticia/pais-passam-madrugada-na-fila-por-atendimento-em-hospital-infantil-do-df.ghtml
- http://www.correiobraziliense.com.br/app/noticia/cidades/2017/08/26/interna_cidadesdf,620910/distrito-federal-tem-deficit-de-5-mil-leitos-na-rede-publica-de-saude.shtml
- https://g1.globo.com/distrito-federal/noticia/saude-do-df-cancela-cirurgia-de-idosa-com-cancer-tres-vezes-por-falta-de-uti.ghtml
- http://radioagencianacional.ebc.com.br/geral/audio/2017-08/rede-publica-de-saude-do-df-enfrenta-reducao-no-numero-de-vagas-de-uti
- https://www.metropoles.com/distrito-federal/saude-df/saude-publica-vira-caso-de-justica-no-distrito-federal
- https://g1.globo.com/df/distrito-federal/noticia/adolescente-consegue-vaga-em-uti-mas-falta-de-transporte-impede-transferencia.ghtml
- https://www.metropoles.com/distrito-federal/saude-df/reorganizacao-no-ihbdf-deixa-pacientes-com-doencas-raras-na-mao
- https://g1.globo.com/df/distrito-federal/noticia/insulina-e-outros-45-medicamentos-estao-em-falta-na-farmacia-de-alto-custo-do-df.ghtml
- http://www.jornaldebrasilia.com.br/cidades/falta-de-atendimento-medico-provoca-tumultos-em-hospitais-no-df/

**Comment by alvesisaque** [comment]
Gente, não utilizem referência ao SUS pq o nosso foco é a gestão da saúde pública no DF não o sistema em si.

Não podemos falar mal do nosso cliente, apenas apresentar de forma clara e serena o problema que a população e eles enfrentam, pq estamos resolvendo um problema que o cliente também enfrenta. 

Atentem-se a esses detalhes!

**Comment by BeatrizHanae** [comment]
@egewarth PO, você poderia me informar melhor sobre qual a metodologia utilizada atualmente para essa gestão de controle que o app iria substituir ou ser um complementar?

**Comment by gdeusdara** [comment]
@alvesisaque @egewarth gente, precisa fazer o diagrama de Fishbone já nessa sprint?

**Comment by alvesisaque** [comment]
@gdeusdara já vamos fazer sim, já temos o problema e é bom ir trabalhando em cima dele!

**Comment by egewarth** [comment]
@BeatrizHanae , oq eles usam atualmente é o TrakCare, um software proprietário imenso, nele são geradas as tabelas de escala. Na reunião de ontem eu perguntei mas parece que os dados de materiais não ficam nesse sistema, segundo oq a moça falou.

**Comment by gdeusdara** [comment]
@egewarth era isso que tu queria na parte de alternativas e concorrencia?

**Comment by egewarth** [comment]
@gdeusdara @BeatrizHanae @vitorl-s , o documento não está muito bem formatado, ta cheio de negritos e tamanhos diferentes. Ahh, aquelas imagens estão muitooo grandes, principalmente a do TrakCare, as referencias estão erradas tbm, deem uma olhada em algum dos docs que a gente fez.
Sobre o conteúdo, é +/- aquilo mesmo, mas se puder pesquisar apps relacionados a coisas médicas ia ser bom tbm.

**Comment by vitorl-s** [comment]
@egewarth to terminando de formatar e finalizar o documento agora!

**Comment by egewarth** [comment]
blz, assim que finalizar o doc dá um commit com Fix #21 <comentário normal do commit> e abre um PR. Eu  vou analizar

**Comment by BeatrizHanae** [comment]
Eu pesquisei apps, apareceram dois: Hospital Sírio-Libanês, referência mundial na área de saúde, e Hospital Santa Catarina, mas ambos são mais voltados para o público, até realizei cadastro neles para ver mais detalhado. Para gestão em si não consigo acesso por não possuir acesso liberado.
Mas achei essas duas notícias sobre: 

- https://g1.globo.com/bemestar/noticia/aplicativo-de-gestao-hospitalar-monitora-equipe-medica-e-promete-reduzir-custos.ghtml

- http://saudebusiness.com/noticias/4-melhores-aplicativos-para-uso-em-hospitais/

**Comment by egewarth** [comment]
Boa, isso que precisamos.

**Comment by gdeusdara** [comment]
Cara, precisa mudar de AGR pra DULCE

**Comment by BeatrizHanae** [comment]
Adicionar nas definições o significado de AGR -  Acordo de Gestão de Resultados.

**Comment by BeatrizHanae** [comment]
Entrar no safe ágile para ter referência no documentos.
Geral: fazer alinhamento do documento ;
1.2) Reescrever;
2.2) Formatação da instrução do problema, 
2.2 + 2.3) colocar em acordo o diagrama fishbone;
3.1) Colocar ponto final
3.1) Escopo do produto - melhorar;
2.3) Manual -> Trackcare
4.1) Linkar equipe - carla, coach, PO;
4.3) Colocar somente logos;
6- Referencias Bibliograficas: o que é , link , quando foi acessado.

**Comment by BeatrizHanae** [comment]
Revisão do documento de visão:
Entrar no safe ágile para ter referência no documentos.
Geral: fazer alinhamento do documento ;
1.2) Reescrever;
2.2) Formatação da instrução do problema, 
2.2 + 2.3) colocar em acordo o diagrama fishbone;
3.1) Colocar ponto final
3.1) Escopo do produto - melhorar;
2.3) Manual -> Trackcare
4.1) Linkar equipe - carla, coach, PO;
4.3) Colocar somente logos;
6- Referencias Bibliograficas: o que é , link , quando foi acessado.
