### ISSUE TITLE
Criar Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by fepas** [fga-gpp-mds/agr-react-native#22]

**Comment by BeatrizHanae** [comment]
@egewarth @alvesisaque como o app será para a equipe de gestão, o cadastro deles para o login deverá ser realizado por CPF? Eles fazem o cadastro ou teríamos um suporte de cadastros da SES-DF que já concedia o acesso à eles só pelo número de série do servidor ou CPF mesmo é melhor?

**Comment by egewarth** [comment]
Pode fazer com email é senha mesmo, sem pensar tanto nesses detalhes de implementação. Como é um protótipo de média fedelidade essas coisas podem ser mudadas. Sobre o cadastro não sei também
