### ISSUE TITLE
Treimanento 3 - React Native

### ISSUE THREAD

**Issue by alvesisaque** [fga-gpp-mds/agr-react-native#29]
Esse treinamento tem o objetivo auxiliar a equipe de desenvolvimento com a curva de aprendizagem da tecnologia.

Data: 20/03
Local: LDS

**Comment by alvesisaque** [comment]
Não houve o treinamento, por que o ministrante Fábio Daburá não estava bem de saúde. O treinamento foi adiado e substituído por uma reunião de apresentação de escopo.

A nova data ainda não foi definida, mas será realizado ainda na Sprint 1.

**Comment by egewarth** [comment]
@fepas , @BeatrizHanae , @gabibguedes , @gdeusdara , @EzequielDeOliveira, @vitorl-s , @eliseuegewarth , @alvesisaque , @gag2502 
O treinamento de react native do Fábio foi remarcado para sexta no horario do almoço, ele vai tentar complementar o que o Amoêdo deu hoje, mais na parte de acesso aos dados.
