### ISSUE TITLE
Criar Roadmap

### ISSUE THREAD

**Issue by alvesisaque** [fga-gpp-mds/agr-react-native#30]

**Comment by alvesisaque** [comment]
Débito técnico da sprint 1, não foi entregue porque a reunião com o cliente foi na sexta-feira.

**Comment by eliseuegewarth** [comment]
Rascunho do roadmap.
![img_20180325_195809](https://user-images.githubusercontent.com/5272409/37881071-8ddd4ca2-3068-11e8-8a18-7e20d48c07c4.jpg)

**Comment by alvesisaque** [comment]
Adicionar canvas no grupo de especificações
