### ISSUE TITLE
Criar documento de Custos

### ISSUE THREAD

**Issue by alvesisaque** [fga-gpp-mds/agr-react-native#40]
- Procurar possíveis concorrentes
- Estimar o preço de horas trabalhadas
- Custo de infraestrutura
- Custo de material
- Custo de investimento inicial
- Investimento vs retorno
- Quanto custa o projeto (investimento) e quanto custa o produto (retorno)
- https://edisciplinas.usp.br/pluginfile.php/4124564/mod_resource/content/1/aula-12.pdf

**Comment by alvesisaque** [comment]
@egewarth, @eliseuegewarth, @gag2502 

Vamos manter esse documento ou transferimos o conteúdo dele para a documentação da sprint.

Acho que é valido um documento dedicado para os custos, tendo em vista a responsabilidade que ele tras quando falamos de produto!

Podemos mudar o nome dele para representar melhor nossa intenção!

**Comment by gag2502** [comment]
Acho que custo ficaria no Tap e os demais no de Sprint ... Pra deixar a documentação enxuta

**Comment by egewarth** [comment]
Acho que no TAP fica a estimativa apenas. Nas sprints podemos colocar um link para um doc de custos especifico para aquela sprint, como se fosse um preço pelo incremento que foi gerado. Ou, dependendo do tamanho desses custos, colocar no própio doc das sprints. Também acho interessante a gente colocar os custos das sprints anteriores, como um incremento mesmo, tipo aquele "i = i + ni" fazendo do novo custo uma somatória do custo anterior com o custo da sprint atual.

**Comment by egewarth** [comment]
A tarefa está realizada na issue #75
