### ISSUE TITLE
Adicionar informações pendentes dos membros da equipe

### ISSUE THREAD

**Issue by eliseuegewarth** [fga-gpp-mds/agr-react-native#43]
Adicionar informações pendentes dos membros da equipe.
Cada membro é responsável por editar suas informações.

 - [x] @gag2502
 - [x] @alvesisaque
 - [x] @egewarth
 - [x] @BeatrizHanae
 - [x] @EzequielDeOliveira
 - [x] @fepas
 - [x] @gabibguedes
 - [x] @gdeusdara
 - [x] @vitorl-s

[Arquivo](../../AGR-APP-react-native/blob/master/docs/equipe.md)

**Comment by eliseuegewarth** [comment]
As submissões devem ser feitas na branch 43_atualiza_informacao_equipe, seguindo o padrão estabelecido em https://github.com/fga-gpp-mds/AGR-APP-react-native/blob/master/CONTRIBUTING.md

**Comment by egewarth** [comment]
@BeatrizHanae , @gag2502 , @EzequielDeOliveira, @fepas vocês não marcaram a alteração de email de vocês, caso não tenham feito, façam, caso tenham feito, marquem que fizeram.
