### ISSUE TITLE
Criação de repositório para documentação

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#47]
Professora Carla, para facilitar o deploy, integração continua e boas praticas de projeto nós vamos usar 2 repositórios, um para o back(API-Node) e um para o front(App-React). 
Nós pensamos em duas abordagens possiveis:

1. Centralizar a documentação em um dos repositórios e duplicar as  diretrizes da comunidade como CONTRIBUTING.md, CODE_OF_CONDUCT.md, issue_template.md e pull-request_template.md. 

2. Colocar os documentos em um outro repositório só de documentação e colocar links para ele em ambos os projetos. 

Optamos por lhe consultar antes de tomar essa decisão pois envolve a organização da disciplina, aguardamos o retorno.

**Comment by alvesisaque** [comment]
Essa issue não é mais necessária, pois já tiramos a duvida com a professora!
