### ISSUE TITLE
Refatorar guia de contribuição

### ISSUE THREAD

**Issue by vitorl-s** [fga-gpp-mds/agr-react-native#55]

**Comment by egewarth** [comment]
@vitorl-s , Falta colocar os labels. vê aqui https://github.com/fga-gpp-mds/agr-react-native/labels oq significa cada um.

**Comment by BeatrizHanae** [comment]
Revisão do Guia de Contribuição:

- [ ] Estrutura ruim, escrever de forma mais harmônica o documento, as instruções; 

- [ ] Revisar os links de acesso (template da issue, template da pull request, etc);

- [ ] Política de Commit -> inserir as instruções sobre como fazer o commit ser valido também para o Co-autor;

- [ ] Especificar melhor o uso do português, exemplo, escrever commit em gerúndio, issue no infinitivo, etc.

- [ ]  Colocar referências.

**Comment by BeatrizHanae** [comment]
@fga-gpp-mds/agr-app gente,  na "Política de Branches", está descrito sobre a branch development, mas vocês definiram retirar ela né? Ai no caso não seria melhor retirar a descrição? Até porque tem link nela que não encaminha para lugar nenhum.

**Comment by egewarth** [comment]
@BeatrizHanae Esquecemos de retirar, obrigado pelo feedback
