### ISSUE TITLE
Criar Lexico 

### ISSUE THREAD

**Issue by EzequielDeOliveira** [fga-gpp-mds/agr-react-native#56]
# Criação do lexico

Criar o lexico do projeto

**Comment by egewarth** [comment]
E essas Labels todas @EzequielDeOliveira ? 
Avançado e iniciante ao mesmo tempo?
Acho que não tem haver com Arquitetura.
Vê aqui https://github.com/fga-gpp-mds/agr-react-native/labels oq é cada um.

**Comment by egewarth** [comment]
Os assignes é interessante marcar no planejamento da Sprint apenas, quando for definido o pareamento.
