### ISSUE TITLE
Refatoração do documento de visão

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#65]
Oq deve ser feito:
- Adequar documento de visão ao novo escopo;
- Adequar diagrama de fishbone;
- Retirar difinições e acrônimos;
- Modificar oportunidade de negocio;
- Modoficar descrição do problema;
- Modificar visão geral do produto;
- Descrição das partes envolvidas.

@gdeusdara , @fepas , @EzequielDeOliveira usem @fga-gpp-mds/eps-agr para as dúvidas.

**Comment by alvesisaque** [comment]
@eliseuegewarth responde eles ai

**Comment by gag2502** [comment]
Dulce é bem mais bonito ! 😉

**Comment by eliseuegewarth** [comment]
@gdeusdara 
- Modifique todos os lugares que citam AGR-APP para Dulce
- Explique o que significa Dulce(aquela sigla) e;
- Qual o papel do APP Dulce no contexto da saúde pública do DF.

**Comment by EzequielDeOliveira** [comment]
ok!

**Comment by EzequielDeOliveira** [comment]
quanto a citar dulce , e melhor apenas Dulce , ou fica melhor citar com D.U.L.C.E?

**Comment by egewarth** [comment]
Coloca no lexico Dulce: dispositivo blablabla... e quando for usar usa Dulce
Pra n ficar feio

**Comment by gag2502** [comment]
@EzequielDeOliveira Achei D.U.L.C.E meio estranho kkk Mas, digam o que acham @eliseuegewarth @egewarth @alvesisaque

**Comment by egewarth** [comment]
Respondi ai @gag2502

**Comment by gag2502** [comment]
@EzequielDeOliveira Perfeito ! (Esse comentário é extremamente a cara do professor André, quase um bordão dela kkk )

**Comment by gag2502** [comment]
@gag2502 dele*

**Comment by egewarth** [comment]
Então, como eu falei, o documento do Léxico serve pra esses casos, a explicação da palavea deve ser feita nele. Dulce: Dispositivo Unificado de coLaboração para Construção de Escala.

**Comment by EzequielDeOliveira** [comment]
@egewarth  na Pré visualização do doc as letras pra dulce tra em negrito como e o esperado kk mas pq aq ficou zuado? help

**Comment by egewarth** [comment]
manda foto

**Comment by EzequielDeOliveira** [comment]
@egewarth Resolvido!!!

**Comment by egewarth** [comment]
oxi, ta mole. Cade o PR?

**Comment by EzequielDeOliveira** [comment]
@egewarth  Posso so fazer o PR ou preciso dar o commit com FIX?

**Comment by egewarth** [comment]
@EzequielDeOliveira não me faça te mandar ler o Código de contribuição dnv ...

**Comment by EzequielDeOliveira** [comment]
kkkkkkkkkkkkkk

**Comment by EzequielDeOliveira** [comment]
tava so testando

**Comment by alvesisaque** [comment]
Atualizem a branch com a master!

**Comment by EzequielDeOliveira** [comment]
@alvesisaque  qual o topico que esta com problema?

**Comment by alvesisaque** [comment]
@EzequielDeOliveira  o 4.1

**Comment by EzequielDeOliveira** [comment]
ok

**Comment by EzequielDeOliveira** [comment]
@alvesisaque  a issue ta fechada como eu acesso ? help

**Comment by egewarth** [comment]
@EzequielDeOliveira, abre uma branch com o nome correto (branch, não issue) e da um commit de hotfix #65 blablabla e abre um novo PR com hotfix blablabla (dizendo pq vc fez)
