### ISSUE TITLE
Refatoração do documento de Arquitetura

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#66]
Oq deve ser feito:

- Criar nova representação da arquitetura (reunir com @gag2502);
- Metas Restrições de Arquitetura (tópico com nome sem mt sentido), mudar de node.js para python django;
- Atualizar doc de arquitetura;
- Outros tópicos ainda não feitos.

@BeatrizHanae, @gabibguedes, @vitorl-s , usem @fga-gpp-mds/eps-agr nas dúvidas.

**Comment by vitorl-s** [comment]
O título da issue está repetido @egewarth

**Comment by alvesisaque** [comment]
Resolvido!

**Comment by BeatrizHanae** [comment]
Bibliografias referentes a arquitetura React Native:

Prototipagem com React Native:
https://medium.com/@oieduardorabelo/prototipagem-com-react-vr-db1031f89853

React Native Architecture explained:
https://www.logicroom.co/react-native-architecture-explained/

**Comment by vitorl-s** [comment]
@gag2502 o diagrama de classes tem que ter cardinalidade também ?

**Comment by gag2502** [comment]
@vitorl-s Sim ! Muito muito muito importante ter ...

**Comment by alvesisaque** [comment]
Atualizem a branch com a master!
