### ISSUE TITLE
Evolução do Protótipo

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#67]
Oq deve ser feito:

Evolução do prototipo de média fidelidade:
- Conter todo o escopo apresentado.

@gdeusdara , @fepas , @EzequielDeOliveira usem @fga-gpp-mds/eps-agr para as dúvidas.

**Comment by fepas** [comment]
Leitura recomendada para todos os desenvolvedores: https://www.thinkwithgoogle.com/intl/pt-br/marketing-resources/ux-e-design/mobile-retail-apps-sites-introduction/

@BeatrizHanae 
@gabibguedes 
@gdeusdara 
@vitorl-s 
@EzequielDeOliveira 
@egewarth

**Comment by gdeusdara** [comment]
Galera, deem ideia sobre o que vai ter na pagina inicial do gestor 
@egewarth 
@eliseuegewarth 
@BeatrizHanae 
@gag2502

**Comment by egewarth** [comment]
@gdeusdara , @fepas, @EzequielDeOliveira, tentem procurar por softwares que usam os recursos de cadastro, edição de perfil, visualização de perfil, agenda (pra escala), envio de foto, alerta de foto e aqueles todos lá.
Um cara que faz design de alguma coisa, ele pesquisa muito como se faz aquela coisa. Quem faz design de cadeira olha milhões de cadeiras pra "se inspirar" ou no caso coletar padrões da cadeira. No caso de vcs é app, então nada mais justo que ir atrás de apps pra saber como faz cada coisa.

**Comment by gag2502** [comment]
@gdeusdara Na minha opinião : tem que ter os dados pessoais dele, básicos mesmo ... Podemos colocar um campo de busca , pra ele filtrar o que quer avaliar ... Isso pode ser um dropdown por áreas ou hospitais também, vocês que sabem ... Como eles que validam atestados , tem que ter ao menos um ícone de notificações para novos atestados

**Comment by fepas** [comment]
Sobre o protótipo,

Nosso escopo ainda é falho em algumas partes, e o na realização do protótipo estão sendo tomadas decisões que podem não ser o que o cliente realmente deseja.

Proponho uma parte da reunião de sabado para elaborar **detalhadamente** as funcionalidades que temos até agora para a apresentação ao cliente.

**Comment by alvesisaque** [comment]
Essas decisões somente  PO pode tomar. Você deve se comunicar melhor com ele e tirar suas duvidas!

O escopo é um dos grandes riscos do nosso projeto, pois até hoje não tivemos acesso ao banco de dados.

Eu acho válido esse detalhamento, poderia transparecer melhor os requisitos para o grupo!

**Comment by egewarth** [comment]
O objetivo do protótipo é validar o escopo com o cliente.
Eu, como PO, sou o representante do cliente, todas as dúvidas que tiverem sobre o protótipo devem ser esclarecidas comigo.

**Comment by egewarth** [comment]
@fepas @gdeusdara @EzequielDeOliveira .
O protótipo ta bacana, ta ganhando a forma de um produto real, gostei.
As telas de login, criar conta, perfil estão boas.
A parte de profissionas é a parte do setor que eu falei, então meu setor é a pagina de profissionais.
O sidebar menu ta ruim, aquele que o @gdeusdara fez ta top, tem bem mais informação, tem icones.
Editar perfil pode deixar, mas provavelmente n vai existir, depende do banco de dados deles.
A main, cara, foge bastante aos padrões de design, mas confesso que não vejo uma outra solução ainda.
A de atestados poderia ser uma imagem, mas por enquanto ta ok.
A de escalas igualmente, provavelmente vai ser modificado, mas pra essa sprint tá ok.
(Lembrem de salvar o Proto.io pra n ter que começar do 0 quando acabar o tempo)
