### ISSUE TITLE
Analizar configuração de ambiente React Native

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#71]
Nessa issue deve ser feito:
- [x]  Coletar informações sobre configurações tipicas de projetos react native
- [x] Como executar projeto
- [ ] Como copilar o projeto (gerar APK)
- [ ] Como colocar em produção

**Comment by eliseuegewarth** [comment]
Link útil em relação a criação de AVDs via commando line:
https://gist.github.com/huston007/bc1e004fbbf91ba129ae

**Comment by eliseuegewarth** [comment]
Esta issue foi executada.
