### ISSUE TITLE
Treinamento React-Native

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#77]
Nesse treinamento:

 - [ ] fetch ou axios 
 - [ ] Lista
 - [ ] ReactRouter

**Comment by BeatrizHanae** [comment]
@fga-gpp-mds/agr-app é amanhã isso? Dia 28/03? Certo?

**Comment by egewarth** [comment]
Isso, esqueci de colocar na issue

**Comment by egewarth** [comment]
Isso, esqueci de colocar na issue
