### ISSUE TITLE
Sugerir temas GitHub Pages

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#78]
Nessa issue deve ser feito:

Sugestão de temas para o nosso GitHub Pages;
Mandar link ou css do tema nos comentarios.

**Comment by eliseuegewarth** [comment]
Por que não utilizamos um tema baseado no design do projeto? (assim que o mesmo for definido)
Se não for utilizar os temas padrão do GitHub Pages, seria interessante que as paginas estejam alinhadas com o design do projeto. 
@fga-gpp-mds/agr-app

**Comment by gag2502** [comment]
Testando meu bot

**Comment by gag2502** [comment]
@gag2502 Testando o bot 2

**Comment by alvesisaque** [comment]
@eliseuegewarth acho válido, mas o design pode demorar e quanto mais postergar essa atividade vai ser difícil colocar os documentos e se adaptar a ele a tempo da R1.

**Comment by eliseuegewarth** [comment]
OK.
Então escolhemos um tema para o Gitub Pages desta release e modificamos na R2 caso necessário.

**Comment by EzequielDeOliveira** [comment]
achei alguns templates que podem ser utilizados 
* https://mmistakes.github.io/hpstr-jekyll-theme/
* http://jekyll.gtat.me/about/
* http://incorporated.sendtoinc.com/
* https://mmistakes.github.io/minimal-mistakes/

**Comment by alvesisaque** [comment]
A priori foi definido esse tema: 
https://github.com/fga-gpp-mds/agr-react-native/issues/52
