### ISSUE TITLE
Configurar integração contínua CI e Análise estática de código

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/agr-react-native#80]
Nessa issue devera ser feito:
- [ ] Integração Contínua com o Travis CI[(projeto de referência)](https://github.com/futurice/pepperoni-app-kit).
- [x] Análise estática de código com Code Climate
- [x] [Métricas de código](https://codeclimate.com/repos/5ab9925ce3905f4bac001020/settings/analysis_config/edit)

**Comment by eliseuegewarth** [comment]
Devemos definir quais métricas serão coletadas pelo codeClimate afim de definir as métricas que serão analisadas e mantidas no projeto.
Votem nas opções que vocês acharem mais adequadas e se possível, comentem seus argumentos.

**Comment by eliseuegewarth** [comment]
Métrica:
 - Similar blocks of code

**Comment by eliseuegewarth** [comment]
Métrica:
 - Return statements

**Comment by eliseuegewarth** [comment]
Métrica:
 - Nested control flow

**Comment by eliseuegewarth** [comment]
Métrica:
 - Method length

**Comment by eliseuegewarth** [comment]
Métrica:
 - Method count

**Comment by eliseuegewarth** [comment]
Métrica:
 - Method complexity

**Comment by eliseuegewarth** [comment]
Métrica:
 - Identical blocks of code

**Comment by eliseuegewarth** [comment]
Métrica:
 - File length

**Comment by eliseuegewarth** [comment]
Métrica:
 - Complex logic

**Comment by eliseuegewarth** [comment]
Métrica:
- Argument count

**Comment by gag2502** [comment]
Ao selecionar minhas preferências, levei em conta o nível de conhecimento atual da tecnologias. Por ser um estágio inicial, talvez aplicar as boas práticas de técnicas de programação pode não ser tão fácil.

**Comment by egewarth** [comment]
Ao dar meu feedback levei em consideração que não temos um conhecimento da linguagem, mas levei em conta os comentarios do @LucasAmoedo sobre replicação de código, por isso não aprovei a analise de blocos de código similares.

**Comment by LucasAmoedo** [comment]
Meio de intruso:

Se vocês vão aplicar folha de estilo, permitam-me recomendar a da Airbnb para React Native. É possível usar o eslint para testar automaticamente (inclusive fazendo o Travis falhar se algo não estiver de acordo). Como ponto negativo, ela pode ser bastante chata. Bastante. E um pouco difícil. Mas ajuda a padronizar código.

**Comment by gag2502** [comment]
@LucasAmoedo Obrigada pela dica @LucasAmoedo 👍 😊 👏

**Comment by eliseuegewarth** [comment]
Das métricas de código listadas e votadas acima foram definidas:

 - **Consideradas**:
 - [x] Return statements
 - [x] Nested control flow
 - [x] Method length
 - [x] Method complexity
 - [x] Identical blocks of code
 - [x] File length
 - [x] Complex logic

 - **Desconsideradas**:
 - [ ] Similar blocks of code
 - [ ] Method count
 - [ ] Argument count
