### ISSUE TITLE
Adequar o projeto às diretrizes da comunidade do GitHub

### ISSUE THREAD

**Issue by eliseuegewarth** [fga-gpp-mds/agr-react-native#9]
Para que o projeto esteja adequado às diretrizes da comunidade do GitHub, deve-se satisfazer todos os padrões recomendados [(aqui)](https://github.com/fga-gpp-mds/AGR-APP-react-native/community).
Issues relacionadas:
- [x] #1 
- [x] #2 
- [x] #4 
- [x] #5 
- [ ] #10

**Comment by eliseuegewarth** [comment]
Issues relacionadas:
#1 #2 #4 #5 #10

**Comment by alvesisaque** [comment]
A milestone dessa issue deve ser alterada para sprint 1, por que na sprint 0 a equipe não tinha o escopo definido, impossibilitando a conclusão de algumas issues.
